### PR TITLE
Fix bugs in Hastus import and export features

### PR DESCRIPTION
**Pull request by jarkkoka**
The following bugs have been found related to the Hastus import feature:
- The direction of the route is not taken into account when connecting Jore routes (journey patterns) to the vehice schedules planned in Hastus. For this reason, the schedules may be associated with wrong routes.
- The route variant is not taken into account when extracting route label from Hastus trip record. Therefore, connecting route variants with Hastus's schedules does not work properly and can lead to schedules being connected with the wrong routes/journey-patterns.
- When connecting the timetables imported from Hastus with the routes (journey patterns), the routes must be filtered so that they are valid at the same time as the imported vehicle schedule frame. 
- One CSV field in the Hastus trip record is skipped. The ignored field looks suspiciously like it contains redundant data, but it exists in both the documentation and the delivered sample files. Because of this, the import feature has probably never worked with real Hastus export files before.
- Currently, when searching for scheduled stop points for journey patterns associated with filtered routes, the stop point selection is non-deterministic in terms of validity period. A fix is needed where for each stop in the journey pattern, the highest priority stop point is selected, which is valid on the day of the observation.

In addition, currently, the logic used to determine which Jore routes relate to which schedules is buried in the CSV data transformation logic. The filtering and validation logic needs to be separated from the data transformation in order to make code cleanly testable.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)

### CODE REVIEW

**Review by culka — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)* status: all files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 229 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfH6kz48e-aUZVBNYMb:-NfH6kz48e-aUZVBNYMc:bwe4w8q) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L229)):*
> ```Kotlin
> 
>     private fun createJourneyPatternReferences(
>         journeyPatterns: List<JoreJourneyPattern>
> ```

Why use a less generic type when no `List` specific methods are used here?
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfL5uJN0dcN8-IVb_VA:-NfL5uJN0dcN8-IVb_VB:b-4fm5br) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/563cab650067f8169cccdb2a97062ede920ad2e9/src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt#L87)):*
> ```Kotlin
>             25.200,
>             "0",
>             "note",
> ```

Currently the only valid value for the first note field is empty or "p", but this does not affect parsing.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfHA6GaA86v0D-UNznW:-NfHA6Gc26DTRmGoK2n0:b-3eb2bn) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt#L277)):*
> ```Kotlin
>     }
> 
>     fun extractRouteLabel(trip: TripRecord): String {
> ```

The logic how Hastus variant are converted to Jore variants is quite complex. There should be comments here why things are done as they are.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)* status: all files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 229 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfH6kz48e-aUZVBNYMb:-Nfk5oBN8hpYllUHDof-:botrinc) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L229)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Why use a less generic type when no `List` specific methods are used here?
</blockquote></details>

You have a point here. In fact, I changed it to be consistent with all the other methods that use `List`. I can change all method parameters of this class to accept `Collection` instead of `List`.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfL5uJN0dcN8-IVb_VA:-Nfk3O_HC2ewNsLAxA-y:b-lp2qqi) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f50edcd1e16858f9b21e976d1e00f1f7739f86ba/src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt#L87)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Currently the only valid value for the first note field is empty or "p", but this does not affect parsing.
</blockquote></details>

Ok, will change it to `p` string.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfHA6GaA86v0D-UNznW:-Nfk6ceO9m1CL3VxAuG8:bim2pwq) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt#L277)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

The logic how Hastus variant are converted to Jore variants is quite complex. There should be comments here why things are done as they are.
</blockquote></details>

Ok, will do.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)* status: 17 of 23 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 229 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfH6kz48e-aUZVBNYMb:-NfuA1s7EVT_q0dSdZLT:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L229)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You have a point here. In fact, I changed it to be consistent with all the other methods that use `List`. I can change all method parameters of this class to accept `Collection` instead of `List`.
</blockquote></details>

Done
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfL5uJN0dcN8-IVb_VA:-NfuA4aG3-75D8Cy8krV:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f50edcd1e16858f9b21e976d1e00f1f7739f86ba/src/test/kotlin/fi/hsl/jore4/hastus/util/CsvReaderTest.kt#L87)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, will change it to `p` string.
</blockquote></details>

Done

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)* status: 16 of 23 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfHA6GaA86v0D-UNznW:-NfuWUU659SGcOPn-Fud:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt#L277)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, will do.
</blockquote></details>

Done

**Review by culka — APPROVED** [review]
Looks good to me!

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-:-NfyUuCM4-Fhw6C0Pq59:b9j9n3q)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 229 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfH6kz48e-aUZVBNYMb:-NfyQX7u5xEiil1KDgNI:b-ec019s) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L229)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Excellent!
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/util/CollectionUtil.kt` line 6 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfySTUE71IWF2ax82Nr:-NfySTUE71IWF2ax82Ns:b-4yksl3) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b1aed4c2f9c3e7c9ee62b282f02be914d549e024/src/main/kotlin/fi/hsl/jore4/hastus/util/CollectionUtil.kt#L6)):*
> ```Kotlin
> 
>     fun <T> filterOutConsecutiveDuplicates(coll: Collection<T>): List<T> {
>         val list = mutableListOf<T>()
> ```

I've done mapping which depends on the previous value using `.zipWithNext()` previously, so
`coll.zipWithNext().filter { (first, second) -> first != second }.map { it.first }`
style solution would be a more functional style option.

The current implementation is fine, though.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfHA6GaA86v0D-UNznW:-NfyRLlYEOyQRpwXkBVy:be0zu03) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/702a6ef12d7903630d27c789137af75483a74d0d/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ConversionsFromHastus.kt#L277)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thank you! :+1:

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/util/CollectionUtil.kt` line 6 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/34#-NfySTUE71IWF2ax82Nr:-NfymYs42H9-EpTQiAaW:b-7qk0sm) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b1aed4c2f9c3e7c9ee62b282f02be914d549e024/src/main/kotlin/fi/hsl/jore4/hastus/util/CollectionUtil.kt#L6)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

I've done mapping which depends on the previous value using `.zipWithNext()` previously, so
`coll.zipWithNext().filter { (first, second) -> first != second }.map { it.first }`
style solution would be a more functional style option.

The current implementation is fine, though.
</blockquote></details>

Yes, it would be more functional and concise, but probably not easier to read, since handling the last item requires adding an extra dummy element to the list.

```kotlin
(coll + null).zipWithNext().filter { (first, second) -> first != second }.mapNotNull { it.first }
```

**Pull request merged**
