### PR TITLE
Add integration tests to cover successful case and some common known exceptions

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 34 files reviewed, 3 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZNsLhCn-Nl0rl6WNY:-NkZNsLiBO6VF1MrcMaW:bj0mhv4) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/README.md#L12)):*
> ```Markdown
> - JDK17+
> - Node.js >= 18.18.2
> - Yarn 1.x
> ```

In timetables-api README there's a `Submodules` section, should we maybe duplicate that here?
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt` line 190 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkWHNcu4xvcdiUpz_bq:-NkWHNcu4xvcdiUpz_br:b-mmjrfr) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt#L190)):*
> ```Kotlin
>     }
> 
>     // This should actually never occur but the output format is tested anyway.
> ```

This made me wonder _why_ can this situation never happen.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 52 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZTm1E8uZxgz6xiNpI:-NkZTm1E8uZxgz6xiNpJ:b-bm4rb5) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L52)):*
> ```Kotlin
>     @Test
>     fun `when journey-pattern-ref exists for both directions`() {
>         populateDatabaseFromDataset("datasets/journey_pattern_ref_100_starting_2023.json")
> ```

I think I might have implemented these tests with one JSON as a base (this starting_2023), and modified that on each test since the changes are rather trivial. With that you would see what actually is changed between the datasets. Now there's a lot of duplication between the JSONs: they are copypasted with just couple of properties modified.
But this is fine as well, since the JSONs are easy enough to digest, and also this way there's less logic in tests itself which is good. :ok_hand: 
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 71 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZUVNy74_Ob56BASnS:-NkZUVNy74_Ob56BASnT:bdkevmd) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L71)):*
> ```Kotlin
>         }
> 
>         // Fails for the first journey-pattern/route encountered that happens to be the outbound
> ```

This is deterministic I hope? That is, does not rely on the order in which these are returned from DB (unless there's an ORDER BY) or something?
___
*[`src/test/resources/application-test.properties` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZQOXg-1FVnvzzFOmo:-NkZQOXg-1FVnvzzFOmp:b-fwdzy3) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/resources/application-test.properties#L8)):*
> ```INI
> jore4.db.password=@test.jore4.db.password@
> 
> logging.level.fi.hsl.jore4.hastus.service.importing=DEBUG
> ```

Was this left here on purpose?

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 34 files reviewed, 3 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZNsLhCn-Nl0rl6WNY:-Nk_1ZOQB9HlLMaeL5ne:b-sisr8b) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/README.md#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

In timetables-api README there's a `Submodules` section, should we maybe duplicate that here?
</blockquote></details>

Ok, good suggestion. I will do that.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt` line 190 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkWHNcu4xvcdiUpz_bq:-Nk_04tT3V-0l1yKBaci:b-hfeaxv) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt#L190)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This made me wonder _why_ can this situation never happen.
</blockquote></details>

Basically, this is because this exception is raised from the data transformation/conversion step (Hastus booking record -> Jore vehicle schedule frame), which happens after a corresponding journey pattern reference has been found for each Hastus trip. In principle, there is redundant error checking and all these errors should be caught in the first step.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 52 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZTm1E8uZxgz6xiNpI:-Nk_1e73CXaoqmK-MO-C:b-y4s2zy) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L52)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think I might have implemented these tests with one JSON as a base (this starting_2023), and modified that on each test since the changes are rather trivial. With that you would see what actually is changed between the datasets. Now there's a lot of duplication between the JSONs: they are copypasted with just couple of properties modified.
But this is fine as well, since the JSONs are easy enough to digest, and also this way there's less logic in tests itself which is good. :ok_hand:
</blockquote></details>

Ok, this is a reasonable suggestion. I'll check if it can be done with relatively little effort.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 71 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZUVNy74_Ob56BASnS:-Nk_-kHP68rc2f-8TPsO:b-hhwg8t) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L71)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is deterministic I hope? That is, does not rely on the order in which these are returned from DB (unless there's an ORDER BY) or something?
</blockquote></details>

The order is dictated by the Hastus booking record file. So, the order is deterministic.
___
*[`src/test/resources/application-test.properties` line 8 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZQOXg-1FVnvzzFOmo:-Nk_-XU16C8SBCZVPb-L:b-2yctbv) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/src/test/resources/application-test.properties#L8)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Was this left here on purpose?
</blockquote></details>

I left the debug level on purpose because it makes testing a bit easier.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 34 files reviewed, 3 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkZNsLhCn-Nl0rl6WNY:-Nk_6wG844GxJRHLk3Pz:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d751b096e6cc42eb49ca894df0eaf026eb22deae/README.md#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, good suggestion. I will do that.
</blockquote></details>

Done

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @culka and @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-Nk_qGEy7FPHsYCw30Ch:-Nk_qGEy7FPHsYCw30Ci:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/a9f2ae68b4f3965e08d2ee5b440aa4a8e5db0656/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L80)):*
> ```Kotlin
>         }.also { exception ->
>             // Fails for the first journey-pattern/route encountered that happens to be the outbound
>             // direction for the line "100" (as this is the first Hastus trip in the file.
> ```





_Suggestion:_
```Kotlin
// direction for the line "100" (as this is the first Hastus trip in the file).
```

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt` line 80 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-Nk_qGEy7FPHsYCw30Ch:-NknxMjAA0QqMwVDSiF9:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/a9f2ae68b4f3965e08d2ee5b440aa4a8e5db0656/src/test/kotlin/fi/hsl/jore4/hastus/service/importing/ImportServiceTest.kt#L80)):*
> ```Kotlin
>         }.also { exception ->
>             // Fails for the first journey-pattern/route encountered that happens to be the outbound
>             // direction for the line "100" (as this is the first Hastus trip in the file.
> ```

Done.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @culka and @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/TimetablesDatasetExtensions.kt` line 14 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkoXlbu2I6qpa8bAXtI:-NkoXlbu2I6qpa8bAXtJ:bqpo2zh) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/9b6d4657b44a639727264efbfd6e16c5c07a3cec/src/test/kotlin/fi/hsl/jore4/hastus/test/TimetablesDatasetExtensions.kt#L14)):*
> ```Kotlin
> 
>     var childProperties: MutableMap<String, Any?> = this
>     for (token in tokens) {
> ```

This loop is starting to get a bit long. I think this could be further clarified quite a bit by separating the list and map handling, eg.
```
for (token in tokens) {  
    LOGGER.debug { "Getting property: $token" }  
  
    val arrayMatcher: Matcher = PATTERN\_ARRAY.matcher(token)  
    childProperties = if (arrayMatcher.matches()) {  
        getListProperty(childProperties, token, arrayMatcher)  
    } else {  
        getMapProperty(childProperties, token)  
    }  
}
```
and then just split the current loop to these helper functions. Something like this, not a working / tidied example yet:
```
fun getListProperty(  
    childProperties: MutableMap<String, Any?>,  
    token: String,  
    arrayMatcher: Matcher  
): MutableMap<String, Any?> {  
    val propertyName: String = arrayMatcher.group(1)  
  
    val arrayIndex: Int? =  
        arrayMatcher  
            .group(2)  
            .takeUnless { it.isEmpty() }  
            ?.toInt()  
            ?.also {  
                if (it < 0) {  
                    throw IllegalStateException("Index must not be negative: '$token'")  
                }  
            }  
  
    val childElem: Any = childProperties\[propertyName\]  
        ?: throw IllegalStateException("No descendant property was found by name '$propertyName'")  
  
    when (childElem) {  
        is List<\*> -> {  
            if (arrayIndex != null) {  
                @Suppress("UNCHECKED\_CAST")  
                return childElem\[arrayIndex\] as MutableMap<String, Any?>  
            } else {  
                childProperties = mutableMapOf()  
  
                childElem.forEachIndexed { index: Int, elem: Any? \->  
                    childProperties\[index.toString()\] = elem  
                }  
                return childProperties  
            }  
        }  
        // not a List  
        else \-> {  
            throw IllegalStateException("Expected an array but did not get one: '$token'")  
        }  
    }  
}  
  
fun getMapProperty(childProperties: MutableMap<String, Any?>, propertyName: String): MutableMap<String, Any?> {  
    val childElem: Any =  
        childProperties\[propertyName\]  
            ?: throw IllegalStateException("No descendant property was found by name '$propertyName'")  
  
    when (childElem) {  
        is List<\*> -> {  
            // or does an exception need to be thrown here at all?  
            throw IllegalStateException("Expected an array but did not get one: '$propertyName'")  
        }  
        // not a List  
        else \-> {  
            @Suppress("UNCHECKED\_CAST")  
            return childElem as MutableMap<String, Any?>  
        }  
    }  
}
```

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-:-NkpOxpE7J4UIW1zMr1A:bnfp4nl)* status: 0 of 35 files reviewed, all discussions resolved (waiting on @culka)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57)* status: 0 of 35 files reviewed, all discussions resolved (waiting on @culka)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/TimetablesDatasetExtensions.kt` line 14 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/57#-NkoXlbu2I6qpa8bAXtI:-NkpT63_-78flrNM5rFQ:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/9b6d4657b44a639727264efbfd6e16c5c07a3cec/src/test/kotlin/fi/hsl/jore4/hastus/test/TimetablesDatasetExtensions.kt#L14)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This loop is starting to get a bit long. I think this could be further clarified quite a bit by separating the list and map handling, eg.
```
for (token in tokens) {  
    LOGGER.debug { "Getting property: $token" }  
  
    val arrayMatcher: Matcher = PATTERN\_ARRAY.matcher(token)  
    childProperties = if (arrayMatcher.matches()) {  
        getListProperty(childProperties, token, arrayMatcher)  
    } else {  
        getMapProperty(childProperties, token)  
    }  
}
```
and then just split the current loop to these helper functions. Something like this, not a working / tidied example yet:
```
fun getListProperty(  
    childProperties: MutableMap<String, Any?>,  
    token: String,  
    arrayMatcher: Matcher  
): MutableMap<String, Any?> {  
    val propertyName: String = arrayMatcher.group(1)  
  
    val arrayIndex: Int? =  
        arrayMatcher  
            .group(2)  
            .takeUnless { it.isEmpty() }  
            ?.toInt()  
            ?.also {  
                if (it < 0) {  
                    throw IllegalStateException("Index must not be negative: '$token'")  
                }  
            }  
  
    val childElem: Any = childProperties\[propertyName\]  
        ?: throw IllegalStateException("No descendant property was found by name '$propertyName'")  
  
    when (childElem) {  
        is List<\*> -> {  
            if (arrayIndex != null) {  
                @Suppress("UNCHECKED\_CAST")  
                return childElem\[arrayIndex\] as MutableMap<String, Any?>  
            } else {  
                childProperties = mutableMapOf()  
  
                childElem.forEachIndexed { index: Int, elem: Any? \->  
                    childProperties\[index.toString()\] = elem  
                }  
                return childProperties  
            }  
        }  
        // not a List  
        else \-> {  
            throw IllegalStateException("Expected an array but did not get one: '$token'")  
        }  
    }  
}  
  
fun getMapProperty(childProperties: MutableMap<String, Any?>, propertyName: String): MutableMap<String, Any?> {  
    val childElem: Any =  
        childProperties\[propertyName\]  
            ?: throw IllegalStateException("No descendant property was found by name '$propertyName'")  
  
    when (childElem) {  
        is List<\*> -> {  
            // or does an exception need to be thrown here at all?  
            throw IllegalStateException("Expected an array but did not get one: '$propertyName'")  
        }  
        // not a List  
        else \-> {  
            @Suppress("UNCHECKED\_CAST")  
            return childElem as MutableMap<String, Any?>  
        }  
    }  
}
```
</blockquote></details>

Done

**Pull request merged**
