### PR TITLE
Apply length limitations of the fields when exporting data to Hastus

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @culka and @jarkkoka)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-NimwAa--EESksDaKQQl):*
I'd rather you squash these last three commits, feels like they belong together. Now it is, 1.) Service logic implementation, 2.) Refactoring previous commit, 3.) Tests (and also some more changes to the service).
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastus.kt` line 94 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-NimtPck3mDdu3TqWcE4:-NimtPcl0rAHyEkJetUK:bv8xh9j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/0c0f59c30551e8db00917e09a003556b736b1681/src/main/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastus.kt#L94)):*
> ```Kotlin
>     ): String {
>         val majorVariant: String = joreRouteLabel.substringAfter(joreLineLabel)
>         val minorVariant: String = variant ?: ""
> ```

This naming is fine and makes sense, but just wondering is this the only instance where this is used? Though, I couldn't find any other `letterVariant` or `numberVariant` instances either. Guess this is fine.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 87 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-NimyMnc8NX-UpOswlj9:-NimyMnc8NX-UpOswljA:b-x3tjji) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/0c0f59c30551e8db00917e09a003556b736b1681/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L87)):*
> ```Kotlin
>             )
> 
>             assertEquals(name.take(MAX_LENGTH_HASTUS_ROUTE_DESCRIPTION), hastusRoute.description)
> ```

What irks me slightly about this approach is that we basically just copypaste the service implementation to tests here.
If that implementation didn't do what we want, it would be harder to notice.
Though, in this case the implementation is trivial and we are using the language methods and not some library, so maybe this kind of thinking is just being paranoid.

To avoid this "issue" I would usually just hardcode the expected value in tests, instead of generating it.
This couples the tests to the length constants (if they change, tests need to be changed), but I don't think that's just a negative thing.
Though in this case, since the resulting names are quite long (50-100 chars), this would bloat the tests a bit.

Maybe this is fine as is. is cleaner at least, and not there's not really an actual issue.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-:-Nin-nv01foiBm-6en-J:bnfp4nl)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @culka and @jarkkoka)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastus.kt` line 94 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-NimtPck3mDdu3TqWcE4:-Nin0n47B5XBEdDjvXs3:bj4oy0h) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/0c0f59c30551e8db00917e09a003556b736b1681/src/main/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastus.kt#L94)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This naming is fine and makes sense, but just wondering is this the only instance where this is used? Though, I couldn't find any other `letterVariant` or `numberVariant` instances either. Guess this is fine.
</blockquote></details>

In the import feature, this encoding is "reversed" and the route label (with variant) is separated from the `routeVariantId` (direction is removed and `_` character added before "minorVariant"). But this exact encoding is not used elsewhere in this codebase or other repositories, as this is very Hastus-specific.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 87 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-NimyMnc8NX-UpOswlj9:-Nin240eEkd3zG8ttNWH:bl4eivm) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/0c0f59c30551e8db00917e09a003556b736b1681/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L87)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

What irks me slightly about this approach is that we basically just copypaste the service implementation to tests here.
If that implementation didn't do what we want, it would be harder to notice.
Though, in this case the implementation is trivial and we are using the language methods and not some library, so maybe this kind of thinking is just being paranoid.

To avoid this "issue" I would usually just hardcode the expected value in tests, instead of generating it.
This couples the tests to the length constants (if they change, tests need to be changed), but I don't think that's just a negative thing.
Though in this case, since the resulting names are quite long (50-100 chars), this would bloat the tests a bit.

Maybe this is fine as is. is cleaner at least, and not there's not really an actual issue.
</blockquote></details>

Was thinking the same. Maybe I'll just put here the hard-coded strings as expected values.

**Review by Leitsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/52#-:-NinbGf65kpQbdEZ01qV:bnfp4nl)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
