### PR TITLE
Fix rest api

### PR DESCRIPTION
**Pull request by culka**
Fix the rest api by:
- forwarding only cookie and custom x- headers to hasura
- remove use of value classes in JSON
- update dependencies

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKwyN-2nK0CMfbPPQ:-NWCKwyN-2nK0CMfbPPR:b3p5a8w) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L50)):*
> ```Kotlin
>                 request.priority,
>                 request.observationDate,
>                 HasuraHeaders.filterHeaders(headers)
> ```

While reading this, I'm wondering whether Hasura headers are filtered in or out. Please consider making the renames suggested in other file.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKhLTCkzoDMXbrW6_:-NWCKhLTCkzoDMXbrW6a:beik43c) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt#L3)):*
> ```Kotlin
> package fi.hsl.jore4.hastus.api
> 
> class HasuraHeaders {
> ```

For clarity, I'd rename this class to `HeaderUtils` and the method `filterHeaders` to `filterInHasuraHeaders`.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKT1d4iMj5se4c9wB:-NWCKT1d4iMj5se4c9wC:blth2xi) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt#L4)):*
> ```Kotlin
> 
> class HasuraHeaders {
>     companion object {
> ```

You can change `class` to `object` since the class only contains the companion object.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/IJSONB.kt` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCLLTO-Ygg9xLzcfwi:-NWCLLTO-Ygg9xLzcfwj:bnczk08) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/graphql/IJSONB.kt#L4)):*
> ```Kotlin
> 
> // Container to get around type erasure
> class IJSONB(
> ```

Please add comment that "Not declared as value class because lack of support from Jackson."
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/UUIDList.kt` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCLZ1T15aNaxuwhR6S:-NWCLZ1U8-Y4n0X5v3sp:bnczk08) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/graphql/UUIDList.kt#L6)):*
> ```Kotlin
> 
> // Container to get around type erasure
> class UUIDList(
> ```

Please add comment that "Not declared as value class because lack of support from Jackson."

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14)* status: 6 of 14 files reviewed, 5 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKwyN-2nK0CMfbPPQ:-NWCVQ1TA_vJrg1fF3Ml:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L50)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

While reading this, I'm wondering whether Hasura headers are filtered in or out. Please consider making the renames suggested in other file.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/IJSONB.kt` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCLLTO-Ygg9xLzcfwi:-NWCVzJDBkk_c2sa5esa:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/graphql/IJSONB.kt#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Please add comment that "Not declared as value class because lack of support from Jackson."
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/UUIDList.kt` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCLZ1T15aNaxuwhR6S:-NWCVzczEC0GuD3mHkp1:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/graphql/UUIDList.kt#L6)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Please add comment that "Not declared as value class because lack of support from Jackson."
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKhLTCkzoDMXbrW6_:-NWCVQSs7b0x1Ock4ybf:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For clarity, I'd rename this class to `HeaderUtils` and the method `filterHeaders` to `filterInHasuraHeaders`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCKT1d4iMj5se4c9wB:-NWCVQwAAKq1lc4IL720:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/83ddd0b92da0a4af4d2016179a51d21724a4587c/src/main/kotlin/fi/hsl/jore4/hastus/api/HasuraHeaders.kt#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You can change `class` to `object` since the class only contains the companion object.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
Left two small suggestions for you to consider. :lgtm: 

> Reviewed 2 of 14 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-:-NWCsH81BwoIYAm8Zmjc:b-5uslyq)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt` line 97 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCpHXRBBZtIzFDRyWK:-NWCpHXRBBZtIzFDRyWL:b-2seiz2) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/64846ca7ca83dffbeb6b10bd1b3dfd41c3cc37d5/src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt#L97)):*
> ```Kotlin
>         val routes: ExportController.Routes = objectMapper.readValue(jsonString)
> 
>         assertEquals("65x", routes.uniqueLabels[0])
> ```

In case of arrays, I'd put length assert first like below:

```kotlin

    assertEquals(2, routes.uniqueLabels.length)
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt` line 212 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCqXEgB5UfUdDEHDU2:-NWCqXEgB5UfUdDEHDU3:bpkfpna) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/64846ca7ca83dffbeb6b10bd1b3dfd41c3cc37d5/src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt#L212)):*
> ```Kotlin
>             """.trimIndent()
>             val parsed: UUIDListFormat = objectMapper.readValue(jsonString)
>             assertEquals(value[0], parsed.uuidList.content[0])
> ```

Would prefer first asserting the length of `parsed.uuidList`.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt` line 97 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCpHXRBBZtIzFDRyWK:-NWD3FBf6WqJCSPURBlf:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/64846ca7ca83dffbeb6b10bd1b3dfd41c3cc37d5/src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt#L97)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In case of arrays, I'd put length assert first like below:

```kotlin

    assertEquals(2, routes.uniqueLabels.length)
```
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt` line 212 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/14#-NWCqXEgB5UfUdDEHDU2:-NWD2k3m8rSCHrkHsQcC:b-w0mad2) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/64846ca7ca83dffbeb6b10bd1b3dfd41c3cc37d5/src/test/kotlin/fi/hsl/jore4/hastus/test/ObjectMapperTest.kt#L212)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Would prefer first asserting the length of `parsed.uuidList`.
</blockquote></details>

Replaced the indexed value checks with checking equality for the whole list

**Pull request merged**
