### PR TITLE
Fix multiple bugs in Hastus import

### PR DESCRIPTION
**Pull request by jarkkoka**
- Fix handling of timing place codes in import feature
- Fix encoding issues by setting `ISO-8859-1` encoding in appropriate places
- Filter out dead runs while importing timetables

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @culka and @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-Nitb8sv6Y3Afpdi6PUp:-Nitb8sv6Y3Afpdi6PUq:b3rjc9y) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b4f0d77605d1553c4ad02e7b796c1e31e977af8b/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt#L23)):*
> ```Kotlin
>  * @property note Special note. Value 'p' means it's a friday trip
>  * @property note2 Reserved for extra information
>  * @property direction Direction. 1 = outbound, 2 = inbound; null = dead run
> ```

Should there be a comma instead, before the null case as well.



_Suggestion:_
```Kotlin
 * @property direction Direction. 1 = outbound, 2 = inbound, null = dead run
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ImportService.kt` line 199 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-NitcE2rATwlEHF70D26:-NitcE2rATwlEHF70D27:b-foyqpo) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b4f0d77605d1553c4ad02e7b796c1e31e977af8b/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ImportService.kt#L199)):*
> ```Kotlin
>                 .filterIsInstance<TripRecord>()
>                 .filter { trip ->
>                     // Null direction denotes a dead run which is not imported to Jore4.
> ```

Are there plans / need to ever have them in Jore4?
Dead run is a Transmodel term as well, related to journeys. https://www.transmodel-cen.eu/model/index.htm?goto=3:1:1:832

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-Nitb8sv6Y3Afpdi6PUp:-NitdUDP0qdI54w_B5aR:bnnllo0) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b4f0d77605d1553c4ad02e7b796c1e31e977af8b/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt#L23)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should there be a comma instead, before the null case as well.
</blockquote></details>

Ok, that would be more consistent. :)
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ImportService.kt` line 199 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-NitcE2rATwlEHF70D26:-NitdaW2-c_ym6oQ0xIS:bnfwflc) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b4f0d77605d1553c4ad02e7b796c1e31e977af8b/src/main/kotlin/fi/hsl/jore4/hastus/service/importing/ImportService.kt#L199)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Are there plans / need to ever have them in Jore4?
Dead run is a Transmodel term as well, related to journeys. https://www.transmodel-cen.eu/model/index.htm?goto=3:1:1:832
</blockquote></details>

What I remember from earlier discussion, no. But time will tell. At least for now in MVP we don't need to support them.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-Nitb8sv6Y3Afpdi6PUp:-Nite6v56pte9ecjUX3c:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b4f0d77605d1553c4ad02e7b796c1e31e977af8b/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, that would be more consistent. :)
</blockquote></details>

Done

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/53#-:-NitfCfsC1TBFatggSKT:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
