### PR TITLE
Change response format in import API and and JUnit tests for it

### PR DESCRIPTION
**Pull request by jarkkoka**
Also add missing documentation for the import feature in `README.md`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41)* status: all files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAbbrKABYGinXvWEyM:-NhAbbrKABYGinXvWEyN:b-3sddvo) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/README.md#L26)):*
> ```Markdown
> ### Export feature
> 
> `export/routes` Send a JSON body containing the route labels, priority and date for which to produce a CSV file for Hastus.
> ```

Would maybe try to be a bit more explicit that the "export/routes" refers to the endpoint, eg. like this.



_Suggestion:_
```Markdown
`POST /export/routes` Send a JSON body containing the route labels, priority and date for which to produce a CSV file for Hastus.
```
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAbrX392mcf3SALrom:-NhAbrX392mcf3SALron:b2nreh6) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/README.md#L46)):*
> ```Markdown
> ### Import feature
> 
> `import` Send a text body in CSV format containing a Hastus schedule to be imported as a vehicle schedule frame to the Jore4 timetables database.
> ```

Same as above.



_Suggestion:_
```Markdown
`POST /import` Send a text body in CSV format containing a Hastus schedule to be imported as a vehicle schedule frame to the Jore4 timetables database.
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt` line 28 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAf-ioEmeVbR65qvfT:-NhAf-ip8MAPNJUmIZOU:b4xqqh3) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt#L28)):*
> ```Kotlin
> import java.util.UUID
> 
> @ExtendWith(MockKExtension::class)
> ```

We should probably make a habit of adding `@MockKExtension.ConfirmVerification` to every mock suite. To ensure we don't forget any mocked method verifications. See https://mockk.io#automatic-verification-confirmation

These are actually missing from timetables API as well, I will add those.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt` line 118 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAgKfBAe2tGUjqdIXA:-NhAgKfBAe2tGUjqdIXB:b3w6thl) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt#L118)):*
> ```Kotlin
>             .andExpect(
>                 constructExpectedErrorBody(
>                     "Could not find journey pattern reference for Hastus trips with the following route " +
> ```

Maybe not in the scope of this PR, but I think frontend would appreciate if we returned more detailed data when an exception occurs, to ease displaying better error messages. Eg. something like:
```
{  
  "message": "Could not find journey pattern reference for Hastus trips with the following route labels and directions: 123 (outbound),456 (inbound)",  
  "exception": "UnmatchedRoutesWithinImport",  
  "details":  {  
    "unmatchedRoutes": [  
      {  
        "label": 123,  
        "direction": "outbound",  
        "route_id": "DEADBEEF-FEED-C0DE-F00D-ABBA1234ABBA"  
      }  
    ]  
  }  
}
```

In timetables API we kind of try to do this already (though there we don't have any `"exception"` field, which would make it easy to show matching errors messages for exceptions).

If we just throw a plain error message, UI can't really do much with it except show it as is.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt` line 28 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAf-ioEmeVbR65qvfT:-NhAwAcnBru6LdWQtRW1:bytcgso) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/src/test/kotlin/fi/hsl/jore4/hastus/api/ImportControllerTest.kt#L28)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

We should probably make a habit of adding `@MockKExtension.ConfirmVerification` to every mock suite. To ensure we don't forget any mocked method verifications. See https://mockk.io#automatic-verification-confirmation

These are actually missing from timetables API as well, I will add those.
</blockquote></details>

Experimented with it a bit but couldn't get it to work.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAbbrKABYGinXvWEyM:-NhB1f50BYGHmwHj8klK:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/README.md#L26)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would maybe try to be a bit more explicit that the "export/routes" refers to the endpoint, eg. like this.
</blockquote></details>

Done.
___
*[`README.md` line 46 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAbrX392mcf3SALrom:-NhB1eoU-yIpW3HISb5l:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/README.md#L46)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-:-NhB1k1u0-6o8ESCDOVs:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/41#-NhAbbrKABYGinXvWEyM:-NhB1MW3Ecpy13wtu8Ny:b-d94f6t) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/d5a260cb5af661ca1541807bf1d31e09c506a3fa/README.md#L26)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would maybe try to be a bit more explicit that the "export/routes" refers to the endpoint, eg. like this.
</blockquote></details>

I notice you didn't include the leading slash from my suggestions, but I guess this is fine as well.

**Pull request merged**
