### PR TITLE
Fix conversion of Hastus route variant ID in CSV export.

### PR DESCRIPTION
**Pull request by jarkkoka**
The bug concerned `rvariant` rows in exported CSV files.

This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51)* status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieahAu8tC3XyCUAJFk):*
Some elaboration on this might've been useful, if there was some important/specific reason?
___
*[`pom.xml` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nieava5ERcQJWp4ofIT:-Nieava5ERcQJWp4ofIU:b42mjow) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/pom.xml#L16)):*
> ```XML
>     <artifactId>hastus</artifactId>
>     <packaging>jar</packaging>
>     <version>1.2.1</version>
> ```

Sneaky update? I'm assuming this had nothing to do with the bug fix, though it's in the same commit. Or if it did, some in explanation commit would be useful.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_uXo3l1ixyJ2Gd-d:-Nie_uXo3l1ixyJ2Gd-e:b-8a6vp9) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt#L12)):*
> // Sort outbound first and inbound after that.

How this is achieved is quite hidden now, we're at the mercy of `wellKnownNumber` internals. Is this fine? Probably won't be causing any bugs (*knocks wood*) since those are very unlikely to change.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 8 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieZvOZAQZTsaIdrJPD:-NieZvOZAQZTsaIdrJPE:bw8zvet) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L8)):*
> ```Kotlin
>  * Hastus Stop point representing a Jore4 scheduled stop point
>  *
>  * @property identifier Stop label as a 7 number long string NNNNNNN
> ```

Could maybe use the term "digit" here.



_Suggestion:_
```Kotlin
 * @property identifier Stop label as a 7 digit long string NNNNNNN
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_F-y0t72RnKhWxbe:-Nie_F-y0t72RnKhWxbf:b-j9jmi0) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt#L16)):*
> ```Kotlin
>  * @property distanceFromPreviousStop Distance from the previous timing point in meters. Null, if
>  * this stop point is not a timing point.
>  * @property stopType Type of the stop point. 'R' on timing places, 'T' on the first and the last
> ```

To me this would sound more natural without the second `the`.



_Suggestion:_
```Kotlin
 * @property stopType Type of the stop point. 'R' on timing places, 'T' on the first and last
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 32 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NiecNcv2FizI33Hq1W1:-NiecNcv2FizI33Hq1W2:b-1nt4xw) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L32)):*
> ```Kotlin
>         fun `with two-char letter variant`() {
>             assertEquals("BK1", getHastusRouteVariantId("123", "123BK", null, JoreRouteDirection.OUTBOUND))
>             assertEquals("BK2", getHastusRouteVariantId("123", "123BK", null, JoreRouteDirection.INBOUND))
> ```

Is two-char + number variant possible? So something like` getHastusRouteVariantId("123", "123BK", "4", JoreRouteDirection.INBOUND)`. Don't think so if I remember Jore3 behavior correctly, but looking at parameters of the tested function this looks possible.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Niebv4k8GEe2uom09Ow:-Niebv4k8GEe2uom09Ox:bzcim1h) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L42)):*
> ```Kotlin
> 
>         @Test
>         fun `with letter-number variant`() {
> ```

I was initially confused because variant parameter for `getHastusRouteVariantId` here is not a letter-number combination, just a number. But this refers to the result I take it, so the hastus route variant.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51)* status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieahAu8tC3XyCUAJFk):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Some elaboration on this might've been useful, if there was some important/specific reason?
</blockquote></details>

It was for better test coverage and more realistic data. I'll add a mention here.
___
*[`pom.xml` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nieava5ERcQJWp4ofIT:-Niefd5E5SV4wLBpc4I1:b-3m0hfv) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/pom.xml#L16)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Sneaky update? I'm assuming this had nothing to do with the bug fix, though it's in the same commit. Or if it did, some in explanation commit would be useful.
</blockquote></details>

I raised the minor version because of the bug fix.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_uXo3l1ixyJ2Gd-d:-Niefvx8ENzXu4rtI_Zj:b7z9qng) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

> // Sort outbound first and inbound after that.

How this is achieved is quite hidden now, we're at the mercy of `wellKnownNumber` internals. Is this fine? Probably won't be causing any bugs (*knocks wood*) since those are very unlikely to change.
</blockquote></details>

Ok. Maybe I'll then revert this change.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 8 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieZvOZAQZTsaIdrJPD:-Nieg0C91dcaJuzxPxYK:bb77ufg) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L8)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could maybe use the term "digit" here.
</blockquote></details>

Yes.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_F-y0t72RnKhWxbe:-Nieg2-h-btGkXjSCxEY:b-pzf9sj) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt#L16)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

To me this would sound more natural without the second `the`.
</blockquote></details>

Not convinced but I can omit the word.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 32 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NiecNcv2FizI33Hq1W1:-Nieg9c7D4u9-6zsRDLu:b-qqzmy0) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L32)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is two-char + number variant possible? So something like` getHastusRouteVariantId("123", "123BK", "4", JoreRouteDirection.INBOUND)`. Don't think so if I remember Jore3 behavior correctly, but looking at parameters of the tested function this looks possible.
</blockquote></details>

It is possible. I'll add another test for better test coverage.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51)* status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 8 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieZvOZAQZTsaIdrJPD:-Nieh9Sp-K0x6_DyeZrO:b-1xf2ta) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Actually the text is wrong. Jore4 does not have 7-digit stop point identifiers. Will change this.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51)* status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`-- commits` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieahAu8tC3XyCUAJFk):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It was for better test coverage and more realistic data. I'll add a mention here.
</blockquote></details>

Done
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 8 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NieZvOZAQZTsaIdrJPD:-NiejBL50x7ys2TnmB7C:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Actually the text is wrong. Jore4 does not have 7-digit stop point identifiers. Will change this.
</blockquote></details>

Done
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_F-y0t72RnKhWxbe:-NiejDvB3gGi3yVDSfRO:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripStopRecord.kt#L16)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not convinced but I can omit the word.
</blockquote></details>

Done
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt` line 32 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-NiecNcv2FizI33Hq1W1:-NiejH70-yWCsBCNpdKc:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/test/kotlin/fi/hsl/jore4/hastus/service/exporting/ConversionsToHastusTest.kt#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It is possible. I'll add another test for better test coverage.
</blockquote></details>

Done
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-Nie_uXo3l1ixyJ2Gd-d:-NiejI_y0ZX8b4LMZDiM:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/b991f4f762b3db85674ecfbf904f7807096b9ff0/src/main/kotlin/fi/hsl/jore4/hastus/data/format/RouteLabelAndDirection.kt#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok. Maybe I'll then revert this change.
</blockquote></details>

Done

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/51#-:-NihqDTQ2JrNndNoSzA7:bnfp4nl)* status: 0 of 30 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
