### PR TITLE
Hello world API for Jore4 Hastus server

### LINKED ISSUE #964: Create new microservice foundation with which we can import and export data from Hastus
Let's create a new Java or Kotlin microservice that will be used for:
- exporting a csv file from chosen routes that contain necessary information for Hastus (to be defined later in a separate ticket)
- importing a csv file that was generated from Hastus, containing timetable information (to be defined later in a separate ticket)
- it should most probably communicate with the JORE4 database through Hasura (but not in scope for this ticket yet)
- this microservice should implement a hello world REST API for this ticket to be considered completed
- this microservice should be deployed to flux repo (Kubernetes + docker-compose)

### PR DESCRIPTION
**Pull request by culka**
Creates an initial hello world -API for the Hastus import/export server. Contains:

* / JSON hello world GET API
* /actuator/health healthcheck
* Basic unit testing framework
* Docker and docker-compose configuration
* Development script
* Initial documentation and license

Resolves https://github.com/HSLdevcom/jore4/issues/964

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)

### CODE REVIEW

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @culka)

___
*[`Dockerfile` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHYYjE4PGT_Qu8xS8:-NEBHYYjE4PGT_Qu8xS9:b-hpt5a) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/Dockerfile#L32)):*
> ```Dockerfile
> COPY --from=builder /build/target/*.jar /usr/src/jore4-hastus/jore4-hastus.jar
> 
> # read Docker secrets into environment variables and run application
> ```

this comment does not make much sense in the current setup :) I'd just go ahead and download the read-secrets script and call it here, even if there are no secrets here to be used yet
___
*[`development.sh` line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBGimp7mEhmADXTmXi:-NEBGimp7mEhmADXTmXj:brez1n) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/development.sh#L9)):*
> ```Shell
> cd "${WD}"
> 
> DOCKER_COMPOSE_CMD="docker-compose -f ./docker/docker-compose.yml"
> ```

not necessarily in the scope of this PR, but should add the docker-compose bundle download part here too:
https://github.com/HSLdevcom/jore4-flux#docker-compose
___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIRFd0ouEnGeF50sQ:-NEBIRFd0ouEnGeF50sR:b-l44wr0) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L12)):*
> ```Markdown
> * JDK11+
> 
> Uses maven to build the project, use `mvn install` to build the server. You can also run the generated .jar file locally to test the server in port 8080.
> ```

_on_ port :)



_Code quote:_
```Markdown
in port
```
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIion-SwIsZ5mwcML:-NEBIion-SwIsZ5mwcMM:b-2yb80p) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L18)):*
> ```Markdown
> * `start` runs the server in port 3008
> * `stop` stops the container
> * `remove` removes the docker container
> ```

could add two more commands: `build` and `test`
___
*[`README.md` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIVhZ8GVbQA5QztqQ:-NEBIVhZ8GVbQA5QztqR:b-jrhyeg) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L33)):*
> ```Markdown
> 
> * `fi.hsl.jore.hastus.api` package contains the API endpoint definitions
> * `fi.hsl.jore.hastus.confing` package contains the server configuration
> ```

config?



_Code quote:_
```Markdown
confing
```
___
*[`docker/docker-compose.yml` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBGzys-IQAcS7oaMoS:-NEBGzys-IQAcS7oaMoT:b-de17fx) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/docker/docker-compose.yml#L2)):*
> ```YAML
> ---
> version: "1.0"
> ```

let's call this `docker-compose.custom.yml` as the `docker-compose.yml` name is reserved for the e2e bundle
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHnyH4BkuTvP1nBdf:-NEBHnyH4BkuTvP1nBdg:bnb0i1j) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt#L22)):*
> ```Kotlin
>             .anyRequest().denyAll()
>     }
> }
> ```

let's add an empty line to the end of every text file. Could add it to the .editorconfig file (insert_final_newline)
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHlWZ52Q0Gr1UHitx:-NEBHlWZ52Q0Gr1UHity:bmj6tc) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt#L11)):*
> ```Kotlin
> class RestTest {
> 
>     val  ec: ExportController = ExportController()
> ```

is there a whitespace error here?

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)* status: all files reviewed, 12 unresolved discussions (waiting on @culka and @pallost)

___
*[`pom.xml` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_JcpAfCPVZLVwhaR:-NEF_JcpAfCPVZLVwhaS:bfkh6vo) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L28)):*
> ```XML
> 
>         
>         <arrow-core.version>1.1.2</arrow-core.version>
> ```

Probably not needed.



_Code quote:_
```XML
       <arrow-core.version>1.1.2</arrow-core.version>
```
___
*[`pom.xml` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_RBc8i2nrHvRZhNz:-NEF_RBc8i2nrHvRZhO-:bkia6a3) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L31)):*
> ```XML
>         <kotlin-logging-jvm.version>2.1.23</kotlin-logging-jvm.version>
>         <quicktheories.version>0.26</quicktheories.version>
>         <spring-boot.version>2.7.0</spring-boot.version>
> ```

Use the most recent version.



_Code quote:_
```XML
2.7.0
```
___
*[`pom.xml` line 353 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_czs49pIfWZ5w6hl:-NEF_czs49pIfWZ5w6hm:b1dolur) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L353)):*
> ```XML
>         <dependency>
>             <groupId>io.arrow-kt</groupId>
>             <artifactId>arrow-core</artifactId>
> ```

Not needed at least now.



_Code quote:_
```XML
        <dependency>
            <groupId>io.arrow-kt</groupId>
            <artifactId>arrow-core</artifactId>
            <version>${arrow-core.version}</version>
        </dependency>
```
___
*[`README.md` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_rA_7vRr_YlgAjTt:-NEF_rA_7vRr_YlgAjTu:bstx1wi) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L28)):*
> ```Markdown
> ## Technical Documentation
> 
> jore4-hastus is a Spring Boot application written in Kotlin, which implements a REST API for converting Hastus CSV into jore4 data and the reverse, jore4 data into CSV files for Hastus.
> ```

I think this should be in uppercase like in other READMEs of various Jore4 repositories.



_Code quote:_
```Markdown
jore4
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHnyH4BkuTvP1nBdf:-NEFaJsd9JsSqK_E0TyU:bqog7zb) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's add an empty line to the end of every text file. Could add it to the .editorconfig file (insert_final_newline)
</blockquote></details>

Agree.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)* status: all files reviewed, 15 unresolved discussions (waiting on @culka and @pallost)

___
*[`README.md` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6Fx0BPmmUwjWofRa:-NEb6Fx0BPmmUwjWofRb:bo1kp1j) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L47)):*
> ```Markdown
> Also:
> 
> * Use the `final` keyword on all fields, variables, arguments and parameters whose values do not change after assignment.
> ```

This is a Java-specific guideline. Not relevant to Kotlin. Should be removed.



_Code quote:_
```Markdown
 Use the `final` keyword on all fields, variables, arguments and parameters whose values do not change after assignment.
```
___
*[`README.md` line 48 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6Luv6sBLOJ5zAslL:-NEb6Luv6sBLOJ5zAslM:bk7w1hp) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L48)):*
> ```Markdown
> 
> * Use the `final` keyword on all fields, variables, arguments and parameters whose values do not change after assignment.
> * Additionally, minimize the use of mutable variables, using `final` whenever possible.
> ```

Replace `final` with `val` because of Java vs Kotlin.



_Code quote:_
```Markdown
Additionally, minimize the use of mutable variables, using `final` whenever possible.
```
___
*[`README.md` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6WXG7ii9egp1voi0:-NEb6WXG7ii9egp1voi1:bnuofex) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L49)):*
> ```Markdown
> * Use the `final` keyword on all fields, variables, arguments and parameters whose values do not change after assignment.
> * Additionally, minimize the use of mutable variables, using `final` whenever possible.
> * Do not use `?`, nullable, expect whenever absolutely necessary.
> ```

Not sure about this. Maybe could be removed?



_Code quote:_
```Markdown
Do not use `?`, nullable, expect whenever absolutely necessary.
```

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Looks pretty ready to me but there some (copy-paste?) errors in the README.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-:-NEdlDW67TUfQFnJZyqO:b-hxmxmo)* status: all files reviewed, 15 unresolved discussions (waiting on @culka and @pallost)

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)* status: 12 of 13 files reviewed, 15 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`Dockerfile` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHYYjE4PGT_Qu8xS8:-NEKNiXb2ao3HV18SKSp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/Dockerfile#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this comment does not make much sense in the current setup :) I'd just go ahead and download the read-secrets script and call it here, even if there are no secrets here to be used yet
</blockquote></details>

Done.
___
*[`development.sh` line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBGimp7mEhmADXTmXi:-NEKQ6W13Ou-NZN_q35n:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/development.sh#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

not necessarily in the scope of this PR, but should add the docker-compose bundle download part here too:
https://github.com/HSLdevcom/jore4-flux#docker-compose
</blockquote></details>

Done.
___
*[`pom.xml` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_JcpAfCPVZLVwhaR:-NEKHvZ_DO2MpO-IEmhK:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Probably not needed.
</blockquote></details>

Done.
___
*[`pom.xml` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_RBc8i2nrHvRZhNz:-NEKHvzp3SToXGfq5Yp_:b-axxql8) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Use the most recent version.
</blockquote></details>

Updated all the libraries to their newest version in mvnrepository.
___
*[`pom.xml` line 353 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_czs49pIfWZ5w6hl:-NEKI3sd6zchDxRFVERc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/pom.xml#L353)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not needed at least now.
</blockquote></details>

Done.
___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIRFd0ouEnGeF50sQ:-NEQ7PAo328DWF5EVMVs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

_on_ port :)
</blockquote></details>

Done.
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIion-SwIsZ5mwcML:-NEQ7_1c0zt8mvSOV7lf:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could add two more commands: `build` and `test`
</blockquote></details>

Done.
___
*[`README.md` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEF_rA_7vRr_YlgAjTt:-NEQ7hVF6kJfz_PRJda0:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this should be in uppercase like in other READMEs of various Jore4 repositories.
</blockquote></details>

Done.
___
*[`README.md` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBIVhZ8GVbQA5QztqQ:-NEQ7hyKCRIxNRRogyxF:buz5ro0) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/README.md#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

config?
</blockquote></details>

Fixed. :)
___
*[`README.md` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6Fx0BPmmUwjWofRa:-NEdngncDH3C_J7hCrQy:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L47)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is a Java-specific guideline. Not relevant to Kotlin. Should be removed.
</blockquote></details>

Done.
___
*[`README.md` line 48 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6Luv6sBLOJ5zAslL:-NEdnjteBRyXfjp1LxdB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L48)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Replace `final` with `val` because of Java vs Kotlin.
</blockquote></details>

Done.
___
*[`README.md` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6WXG7ii9egp1voi0:-NEdnkJ25MMTv-dvwv4P:b-kfcy8b) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not sure about this. Maybe could be removed?
</blockquote></details>

I like making sure nothing is nullable unless it absolutely needs to be. Fortunately this should not really be a problem with Kotlin. Removed.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHnyH4BkuTvP1nBdf:-NEKL38KD_Pb_SHL8TO0:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt#L22)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

Done.
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBHlWZ52Q0Gr1UHitx:-NEKLAWnC9Vaz-fT_OS9:b-xhy4fx) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is there a whitespace error here?
</blockquote></details>

Indeed there was. Fixed.
___
*[`docker/docker-compose.yml` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEBGzys-IQAcS7oaMoS:-NEKO14EDKcT7wIwaK5E:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/777b6da16ec5e7013d9122fce2047727309c7279/docker/docker-compose.yml#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's call this `docker-compose.custom.yml` as the `docker-compose.yml` name is reserved for the e2e bundle
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1)* status: all files reviewed, 8 unresolved discussions (waiting on @pallost)

___
*[`README.md` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hastus/1#-NEb6WXG7ii9egp1voi0:-NEe04Zk24DDrofxpP1W:bb6sh2i) ([raw file](https://github.com/hsldevcom/jore4-hastus/blob/eae59c09f259dad0cd2a5514dec9b1c7eeb39379/README.md#L49)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

I like making sure nothing is nullable unless it absolutely needs to be. Fortunately this should not really be a problem with Kotlin. Removed.
</blockquote></details>

Ack.

**Pull request merged**
