### PR TITLE
Refactor export-import flow

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
> Reviewed 36 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37)* status: 36 of 41 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/Constants.kt` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-Ng2lHUpD8zn8ngb6hvA:-Ng2lHUpD8zn8ngb6hvB:b-nst1lm) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/44d4f162da582db63ec5350550f196f994176aa6/src/main/kotlin/fi/hsl/jore4/hastus/Constants.kt#L14)):*
> ```Kotlin
> 
>     // priorities for network scope in GraphQL
>     const val ROUTE_PRIORITY_DRAFT = 30
> ```

The priority values _can_ be kept different constants, but there has been an agreement to keep them same for every database.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-Ng2lmSe6ShUijI3mNjR:-Ng2lmSe6ShUijI3mNjS:bh7r3zz) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/44d4f162da582db63ec5350550f196f994176aa6/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L41)):*
> ```Kotlin
>         val uniqueLabels: List<String>,
>         @field:Min(0)
>         @field:Max(Constants.ROUTE_PRIORITY_DRAFT - 1L)
> ```

Why are draft priority routes excluded? This is allowed in the UI and changing it will prevent doing possible preliminary timetable planning in Hastus.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37)* status: 36 of 41 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-Ng2lmSe6ShUijI3mNjR:-Ng3Uhhl0fMLmLVye2uY:beiweok) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/44d4f162da582db63ec5350550f196f994176aa6/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L41)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Why are draft priority routes excluded? This is allowed in the UI and changing it will prevent doing possible preliminary timetable planning in Hastus.
</blockquote></details>

Ok good point. here, there seems to be some confusion regarding the stop points in the draft state, which are excluded. As for the routes, apparently draft versions are wanted to be supported. I will fix this...

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37)* status: 33 of 41 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-Ng2lmSe6ShUijI3mNjR:-Ng3X0IoE7NTJQuzT9OU:bb6un1j) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/44d4f162da582db63ec5350550f196f994176aa6/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok good point. here, there seems to be some confusion regarding the stop points in the draft state, which are excluded. As for the routes, apparently draft versions are wanted to be supported. I will fix this...
</blockquote></details>

Done

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37)* status: 33 of 41 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/Constants.kt` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-Ng2lHUpD8zn8ngb6hvA:-Ng3X59IEQd7e29c8eWw:bx9s6if) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/44d4f162da582db63ec5350550f196f994176aa6/src/main/kotlin/fi/hsl/jore4/hastus/Constants.kt#L14)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

The priority values _can_ be kept different constants, but there has been an agreement to keep them same for every database.
</blockquote></details>

Removed additional draft priority.

**Review by culka — COMMENTED** [review]
Looking really good!

I would add a test case for importing, when there are multiple possible routes to choose from, so the right one is chosen.

> Reviewed 5 of 41 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-:-NgI6XK1-nNWXVcjbXTS:b-yopfmj)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

**Review by jarkkoka — COMMENTED** [review]
Thanks! I will create a separate GH issue and PR for the JUnit tests as discussed in sprint planning.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/37#-:-NgU-kc5BKKPrX12e4uk:bpjoyu9)* status: 40 of 41 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
